/**
 * Fleet Work Queue
 *
 * Decouples task intake from execution. Any trigger source (Slack, GitHub,
 * Notion, ADO, SMS, ...) writes a FleetWorkMessage to Azure Storage Queue.
 * The dispatcher loop reads messages and creates ACI containers.
 *
 * This is the universal intake — every trigger writes the same format.
 */
import { logger } from './logger.js';

// --- Message schema ---

export interface FleetWorkMessage {
  /** Schema version for forward compatibility */
  version: 1;

  /** Unique message ID (generated by the writer, used for dedup) */
  id: string;

  /** Where this request came from */
  source: {
    type: 'slack' | 'github' | 'notion' | 'ado' | 'api' | 'scheduled';
    /** Source-specific reply info (Slack: channel+thread, GitHub: issue comment, etc.) */
    replyTo: ReplyTarget;
    /** Who requested this (display name or ID) */
    requester: string;
  };

  /** What to work on */
  task: {
    /** "org/repo" (GitHub) or "ado:project/repo" (ADO) */
    repoSlug: string;
    /** Fleet goal — may be enriched with work item context by the writer */
    description: string;
    /** Issue/PR/work-item number (if applicable) */
    issueNumber?: string;
    /** Branch to check out or create */
    branch?: string;
  };

  /** Fleet configuration */
  fleet: {
    /** Comma-separated agent names (null = let bootstrap.sh decide) */
    agents?: string;
    /** Timeout in minutes */
    timeoutMinutes?: number;
    /** all-opus, all-sonnet, mixed (default) */
    modelStrategy?: string;
    /** Override target: 'azure' | 'local' (null = auto-resolve) */
    target?: string;
  };

  /** Team context markdown (injected into .claude/team-context.md) */
  teamContext?: string;

  /** ISO timestamp when the message was created */
  createdAt: string;
}

/** Where to send progress updates and the final result */
export type ReplyTarget =
  | { type: 'slack'; channelId: string; threadTs?: string }
  | { type: 'github'; repo: string; issueNumber: number }
  | { type: 'notion'; pageId: string; blockId?: string }
  | { type: 'ado'; org: string; project: string; workItemId: number }
  | { type: 'none' };

// --- Queue operations (Azure Storage Queue via REST API) ---

const STORAGE_ACCOUNT = process.env.ACI_STORAGE_ACCOUNT || 'aifleetprodst';
const QUEUE_NAME = 'fleet-work';
const DLQ_NAME = 'fleet-work-dlq';

/**
 * Get a SAS-free queue URL. When running with MI, we use Entra auth.
 * For local dev, use the storage key from env.
 */
function queueUrl(queue: string): string {
  return `https://${STORAGE_ACCOUNT}.queue.core.windows.net/${queue}`;
}

/**
 * Get an auth header for Azure Storage Queue.
 * Uses MI token when in Azure, storage key when local.
 */
async function getQueueAuthHeader(): Promise<Record<string, string>> {
  // Try MI first (Container App / ACI)
  const identityEndpoint = process.env.IDENTITY_ENDPOINT;
  if (identityEndpoint) {
    const identityHeader = process.env.IDENTITY_HEADER;
    const params = new URLSearchParams({
      'api-version': '2019-08-01',
      resource: 'https://storage.azure.com/',
    });
    const clientId = process.env.ACI_MANAGED_IDENTITY_ID;
    if (clientId) params.set('client_id', clientId);

    const headers: Record<string, string> = { Metadata: 'true' };
    if (identityHeader) headers['X-IDENTITY-HEADER'] = identityHeader;

    const res = await fetch(`${identityEndpoint}?${params}`, { headers });
    if (res.ok) {
      const data = (await res.json()) as { access_token: string };
      return {
        Authorization: `Bearer ${data.access_token}`,
        'x-ms-version': '2021-08-06',
      };
    }
  }

  // Fallback: shared key from env (local dev)
  // For simplicity, use the key directly in the header via SAS-like approach
  // In production, MI auth above should always work
  const storageKey = process.env.ACI_STORAGE_KEY || '';
  if (!storageKey) {
    throw new Error('No MI endpoint and no ACI_STORAGE_KEY — cannot auth to queue');
  }

  // Use account key via x-ms-date + SharedKey auth
  // This is complex to implement manually — for local dev, prefer az CLI or connection string
  throw new Error('SharedKey auth not implemented — use MI auth (run in Azure) or set IDENTITY_ENDPOINT for local testing');
}

/**
 * Enqueue a fleet work message.
 */
export async function enqueueFleetWork(message: FleetWorkMessage): Promise<void> {
  const auth = await getQueueAuthHeader();
  const url = `${queueUrl(QUEUE_NAME)}/messages`;

  // Azure Storage Queue messages are base64-encoded XML
  const messageText = Buffer.from(JSON.stringify(message)).toString('base64');
  const body = `<QueueMessage><MessageText>${messageText}</MessageText></QueueMessage>`;

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      ...auth,
      'Content-Type': 'application/xml',
    },
    body,
  });

  if (!res.ok) {
    throw new Error(`Queue enqueue failed: ${res.status} ${await res.text()}`);
  }

  logger.info({ messageId: message.id, source: message.source.type }, 'Fleet work enqueued');
}

/**
 * Dequeue a fleet work message (with visibility timeout).
 * Returns null if the queue is empty.
 */
export async function dequeueFleetWork(
  visibilityTimeoutSeconds: number = 3600,
): Promise<{ message: FleetWorkMessage; messageId: string; popReceipt: string } | null> {
  const auth = await getQueueAuthHeader();
  const url = `${queueUrl(QUEUE_NAME)}/messages?numofmessages=1&visibilitytimeout=${visibilityTimeoutSeconds}`;

  const res = await fetch(url, {
    headers: { ...auth, Accept: 'application/xml' },
  });

  if (!res.ok) {
    throw new Error(`Queue dequeue failed: ${res.status}`);
  }

  const xml = await res.text();

  // Parse the XML response (minimal parsing — we know the structure)
  const messageTextMatch = xml.match(/<MessageText>([^<]+)<\/MessageText>/);
  const messageIdMatch = xml.match(/<MessageId>([^<]+)<\/MessageId>/);
  const popReceiptMatch = xml.match(/<PopReceipt>([^<]+)<\/PopReceipt>/);

  if (!messageTextMatch || !messageIdMatch || !popReceiptMatch) {
    return null; // Empty queue
  }

  const decoded = Buffer.from(messageTextMatch[1], 'base64').toString('utf-8');
  const message = JSON.parse(decoded) as FleetWorkMessage;

  return {
    message,
    messageId: messageIdMatch[1],
    popReceipt: popReceiptMatch[1],
  };
}

/**
 * Delete a message from the queue (after successful processing).
 */
export async function deleteQueueMessage(
  messageId: string,
  popReceipt: string,
): Promise<void> {
  const auth = await getQueueAuthHeader();
  const url = `${queueUrl(QUEUE_NAME)}/messages/${messageId}?popreceipt=${encodeURIComponent(popReceipt)}`;

  const res = await fetch(url, {
    method: 'DELETE',
    headers: auth,
  });

  if (!res.ok) {
    logger.warn({ messageId, status: res.status }, 'Failed to delete queue message');
  }
}

/**
 * Move a message to the dead-letter queue after repeated failures.
 */
export async function deadLetterMessage(
  message: FleetWorkMessage,
  error: string,
): Promise<void> {
  const auth = await getQueueAuthHeader();
  const url = `${queueUrl(DLQ_NAME)}/messages`;

  const envelope = {
    originalMessage: message,
    error,
    deadLetteredAt: new Date().toISOString(),
  };
  const messageText = Buffer.from(JSON.stringify(envelope)).toString('base64');
  const body = `<QueueMessage><MessageText>${messageText}</MessageText></QueueMessage>`;

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      ...auth,
      'Content-Type': 'application/xml',
    },
    body,
  });

  if (!res.ok) {
    logger.error({ messageId: message.id, status: res.status }, 'Failed to dead-letter message');
  } else {
    logger.info({ messageId: message.id, error }, 'Message dead-lettered');
  }
}

// --- Helpers ---

/**
 * Create a fleet work message from a parsed fleet task config.
 * Used by Slack handler (and future trigger sources) to write to the queue.
 */
export function buildFleetWorkMessage(opts: {
  repoSlug: string;
  description: string;
  issueNumber?: string;
  branch?: string;
  agents?: string;
  timeoutMinutes?: number;
  modelStrategy?: string;
  target?: string;
  teamContext?: string;
  source: FleetWorkMessage['source'];
}): FleetWorkMessage {
  return {
    version: 1,
    id: `fwm-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    source: opts.source,
    task: {
      repoSlug: opts.repoSlug,
      description: opts.description,
      issueNumber: opts.issueNumber,
      branch: opts.branch,
    },
    fleet: {
      agents: opts.agents,
      timeoutMinutes: opts.timeoutMinutes,
      modelStrategy: opts.modelStrategy,
      target: opts.target,
    },
    teamContext: opts.teamContext,
    createdAt: new Date().toISOString(),
  };
}
